In [2]:
import pandas as pd
import numpy as np

In [3]:
adult = pd.read_csv("preprocessed_adult.csv")

print(adult.shape)

adult_copy = adult.drop(['education_10th', 'education_11th', 'education_12th',
       'education_1st-4th', 'education_5th-6th', 'education_7th-8th',
       'education_9th', 'education_Assoc-acdm', 'education_Assoc-voc',
       'education_Bachelors', 'education_Doctorate', 'education_HS-grad',
       'education_Masters', 'education_Preschool', 'education_Prof-school',
       'education_Some-college'], axis = 1)
# education se refere ao nível de escolaridade da pessoa, que é uma categoria ordinal
# tem outra featura chamada education_num que é um ordinal encoding dessa, então não tem necessidade de manter essas

classes_to_int = adult_copy.columns[8:]

adult_copy[classes_to_int] = adult_copy[classes_to_int].astype(int)

adult_copy.info()

(45222, 104)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45222 entries, 0 to 45221
Data columns (total 88 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   income                                     45222 non-null  float64
 1   gender                                     45222 non-null  float64
 2   age                                        45222 non-null  float64
 3   fnlwgt                                     45222 non-null  float64
 4   educational-num                            45222 non-null  float64
 5   capital-gain                               45222 non-null  float64
 6   capital-loss                               45222 non-null  float64
 7   hours-per-week                             45222 non-null  float64
 8   workclass_Federal-gov                      45222 non-null  int64
 9   workclass_Local-gov                        45222 non-null  int64
 10  workclass_Private                          45222 non-null  int64
 11  workclass_Self-emp-inc                     45222 non-null  int64
 12  workclass_Self-emp-not-inc                 45222 non-null  int64
 13  workclass_State-gov                        45222 non-null  int64
 14  workclass_Without-pay                      45222 non-null  int64
 15  marital-status_Divorced                    45222 non-null  int64
 16  marital-status_Married-AF-spouse           45222 non-null  int64
 17  marital-status_Married-civ-spouse          45222 non-null  int64
 18  marital-status_Married-spouse-absent       45222 non-null  int64
 19  marital-status_Never-married               45222 non-null  int64
 20  marital-status_Separated                   45222 non-null  int64
 21  marital-status_Widowed                     45222 non-null  int64
 22  occupation_Adm-clerical                    45222 non-null  int64
 23  occupation_Armed-Forces                    45222 non-null  int64
 24  occupation_Craft-repair                    45222 non-null  int64
 25  occupation_Exec-managerial                 45222 non-null  int64
 26  occupation_Farming-fishing                 45222 non-null  int64
 27  occupation_Handlers-cleaners               45222 non-null  int64
 28  occupation_Machine-op-inspct               45222 non-null  int64
 29  occupation_Other-service                   45222 non-null  int64
 30  occupation_Priv-house-serv                 45222 non-null  int64
 31  occupation_Prof-specialty                  45222 non-null  int64
 32  occupation_Protective-serv                 45222 non-null  int64
 33  occupation_Sales                           45222 non-null  int64
 34  occupation_Tech-support                    45222 non-null  int64
 35  occupation_Transport-moving                45222 non-null  int64
 36  relationship_Husband                       45222 non-null  int64
 37  relationship_Not-in-family                 45222 non-null  int64
 38  relationship_Other-relative                45222 non-null  int64
 39  relationship_Own-child                     45222 non-null  int64
 40  relationship_Unmarried                     45222 non-null  int64
 41  relationship_Wife                          45222 non-null  int64
 42  race_Amer-Indian-Eskimo                    45222 non-null  int64
 43  race_Asian-Pac-Islander                    45222 non-null  int64
 44  race_Black                                 45222 non-null  int64
 45  race_Other                                 45222 non-null  int64
 46  race_White                                 45222 non-null  int64
 47  native-country_Cambodia                    45222 non-null  int64
 48  native-country_Canada                      45222 non-null  int64
 49  native-country_China                       45222 non-null  int64
 50  native-country_Columbia                    45222 non-null  int64
 51  native-country_Cuba                        45222 non-null  int64
 52  native-country_Dominican-Republic          45222 non-null  int64
 53  native-country_Ecuador                     45222 non-null  int64
 54  native-country_El-Salvador                 45222 non-null  int64
 55  native-country_England                     45222 non-null  int64
 56  native-country_France                      45222 non-null  int64
 57  native-country_Germany                     45222 non-null  int64
 58  native-country_Greece                      45222 non-null  int64
 59  native-country_Guatemala                   45222 non-null  int64
 60  native-country_Haiti                       45222 non-null  int64
 61  native-country_Holand-Netherlands          45222 non-null  int64
 62  native-country_Honduras                    45222 non-null  int64
 63  native-country_Hong                        45222 non-null  int64
 64  native-country_Hungary                     45222 non-null  int64
 65  native-country_India                       45222 non-null  int64
 66  native-country_Iran                        45222 non-null  int64
 67  native-country_Ireland                     45222 non-null  int64
 68  native-country_Italy                       45222 non-null  int64
 69  native-country_Jamaica                     45222 non-null  int64
 70  native-country_Japan                       45222 non-null  int64
 71  native-country_Laos                        45222 non-null  int64
 72  native-country_Mexico                      45222 non-null  int64
 73  native-country_Nicaragua                   45222 non-null  int64
 74  native-country_Outlying-US(Guam-USVI-etc)  45222 non-null  int64
 75  native-country_Peru                        45222 non-null  int64
 76  native-country_Philippines                 45222 non-null  int64
 77  native-country_Poland                      45222 non-null  int64
 78  native-country_Portugal                    45222 non-null  int64
 79  native-country_Puerto-Rico                 45222 non-null  int64
 80  native-country_Scotland                    45222 non-null  int64
 81  native-country_South                       45222 non-null  int64
 82  native-country_Taiwan                      45222 non-null  int64
 83  native-country_Thailand                    45222 non-null  int64
 84  native-country_Trinadad&Tobago             45222 non-null  int64
 85  native-country_United-States               45222 non-null  int64
 86  native-country_Vietnam                     45222 non-null  int64
 87  native-country_Yugoslavia                  45222 non-null  int64
dtypes: float64(8), int64(80)
memory usage: 30.4 MB

In [4]:
adult_copy['marital-status_Married-civ-or-AF-spouse'] = adult_copy['marital-status_Married-civ-spouse'] | adult_copy['marital-status_Married-AF-spouse']
adult_copy = adult_copy.drop(['marital-status_Married-AF-spouse', 'marital-status_Married-civ-spouse'], axis = 1)
# só existe cerca de 30 pessoas com a classe Married_AF_spouse, e elas são semelhantes em dist. ao Married-civ-spouse
# então resolvi juntar para reduzir a dimensionalidade, outra opção seria só retirar essas 30

In [5]:
countrys = adult_copy.columns[45:86] # pegando as colunas dos native-country

In [6]:
adult_copy['region_US-and-Cuba'] = adult_copy['native-country_United-States'] | adult_copy['native-country_Cuba']

adult_copy['region_Western'] = adult_copy['native-country_England'] | adult_copy['native-country_Germany'] | \
                               adult_copy['native-country_Canada'] | adult_copy['native-country_Italy'] | \
                               adult_copy['native-country_France'] | adult_copy['native-country_Greece'] | \
                               adult_copy['native-country_Philippines']

adult_copy['region_ThirdWorld-and-Portugal'] = adult_copy['native-country_Mexico'] | adult_copy['native-country_Puerto-Rico'] | \
                                               adult_copy['native-country_Honduras'] | adult_copy['native-country_Jamaica'] | \
                                               adult_copy['native-country_Columbia'] | adult_copy['native-country_Laos'] | \
                                               adult_copy['native-country_Portugal'] | adult_copy['native-country_Haiti'] | \
                                               adult_copy['native-country_Dominican-Republic'] | adult_copy['native-country_El-Salvador'] | \
                                               adult_copy['native-country_Guatemala'] | adult_copy['native-country_Peru'] | \
                                               adult_copy['native-country_Trinadad&Tobago'] | adult_copy['native-country_Outlying-US(Guam-USVI-etc)'] | \
                                               adult_copy['native-country_Nicaragua'] | adult_copy['native-country_Vietnam'] | \
                                               adult_copy['native-country_Holand-Netherlands']

adult_copy['region_Eastern'] = adult_copy['native-country_India'] | adult_copy['native-country_Iran'] | \
                               adult_copy['native-country_Cambodia'] | adult_copy['native-country_Taiwan'] | \
                               adult_copy['native-country_Japan'] | adult_copy['native-country_Yugoslavia'] | \
                               adult_copy['native-country_China'] | adult_copy['native-country_Hong']

adult_copy['region_Others'] = adult_copy['native-country_South'] | adult_copy['native-country_Poland'] | \
                              adult_copy['native-country_Ireland'] | adult_copy['native-country_Hungary'] | \
                              adult_copy['native-country_Scotland'] | adult_copy['native-country_Thailand'] | \
                              adult_copy['native-country_Ecuador']

# aqui eu juntei os países por região, mas também levei em consideração a distribuição deles no dataset, tentando manter dist parecidas juntas

adult_copy = adult_copy.drop(countrys, axis = 1)

In [7]:
adult_copy = adult_copy.drop('fnlwgt', axis = 1)
# dropando o fnlwgt que é geralmente não-utilizado

adult_copy.info() 
# resultou em 50 colunas, tinhamos 105 antes, poderia tirar mais mas acho que não há tanta necessidade

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45222 entries, 0 to 45221
Data columns (total 50 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   income                                   45222 non-null  float64
 1   gender                                   45222 non-null  float64
 2   age                                      45222 non-null  float64
 3   educational-num                          45222 non-null  float64
 4   capital-gain                             45222 non-null  float64
 5   capital-loss                             45222 non-null  float64
 6   hours-per-week                           45222 non-null  float64
 7   workclass_Federal-gov                    45222 non-null  int64
 8   workclass_Local-gov                      45222 non-null  int64
 9   workclass_Private                        45222 non-null  int64
 10  workclass_Self-emp-inc                   45222 non-null  int64
 11  workclass_Self-emp-not-inc               45222 non-null  int64
 12  workclass_State-gov                      45222 non-null  int64
 13  workclass_Without-pay                    45222 non-null  int64
 14  marital-status_Divorced                  45222 non-null  int64
 15  marital-status_Married-spouse-absent     45222 non-null  int64
 16  marital-status_Never-married             45222 non-null  int64
 17  marital-status_Separated                 45222 non-null  int64
 18  marital-status_Widowed                   45222 non-null  int64
 19  occupation_Adm-clerical                  45222 non-null  int64
 20  occupation_Armed-Forces                  45222 non-null  int64
 21  occupation_Craft-repair                  45222 non-null  int64
 22  occupation_Exec-managerial               45222 non-null  int64
 23  occupation_Farming-fishing               45222 non-null  int64
 24  occupation_Handlers-cleaners             45222 non-null  int64
 25  occupation_Machine-op-inspct             45222 non-null  int64
 26  occupation_Other-service                 45222 non-null  int64
 27  occupation_Priv-house-serv               45222 non-null  int64
 28  occupation_Prof-specialty                45222 non-null  int64
 29  occupation_Protective-serv               45222 non-null  int64
 30  occupation_Sales                         45222 non-null  int64
 31  occupation_Tech-support                  45222 non-null  int64
 32  occupation_Transport-moving              45222 non-null  int64
 33  relationship_Husband                     45222 non-null  int64
 34  relationship_Not-in-family               45222 non-null  int64
 35  relationship_Other-relative              45222 non-null  int64
 36  relationship_Own-child                   45222 non-null  int64
 37  relationship_Unmarried                   45222 non-null  int64
 38  relationship_Wife                        45222 non-null  int64
 39  race_Amer-Indian-Eskimo                  45222 non-null  int64
 40  race_Asian-Pac-Islander                  45222 non-null  int64
 41  race_Black                               45222 non-null  int64
 42  race_Other                               45222 non-null  int64
 43  race_White                               45222 non-null  int64
 44  marital-status_Married-civ-or-AF-spouse  45222 non-null  int64
 45  region_US-and-Cuba                       45222 non-null  int64
 46  region_Western                           45222 non-null  int64
 47  region_ThirdWorld-and-Portugal           45222 non-null  int64
 48  region_Eastern                           45222 non-null  int64
 49  region_Others                            45222 non-null  int64
dtypes: float64(7), int64(43)
memory usage: 17.3 MB

In [8]:
adult_copy.to_csv("binned_adult.csv", index = False)

In [9]:
compas = pd.read_csv("preprocessed_compas.csv")

print(compas.shape)

compas_copy = compas.dropna()
compas_copy.to_csv("preprocessed_compas_clean.csv", index = False)

(4743, 27)